image: golang:1.11

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - vendor/

build and test:
  script:
  - make dependencies
  - make lint
  - make test