language: go
sudo: false

go:
  - 1.x

cache:
  directories:
    - vendor

env:
  global:
    - ARTIFACTS_DIR=artifacts

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y zip

install:
  - make dependencies

script:
  - make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash) -s ./.cover
  - make cmdx

addons:
  artifacts:
    s3_region: ${ARTIFACTS_S3_REGION}
    working_dir: ${ARTIFACTS_DIR}
    paths:
      - $(ls *.zip | tr "\n" ":")
      - $(ls *.tgz | tr "\n" ":")
    target_paths:
      - /${TRAVIS_REPO_SLUG}/${TRAVIS_COMMIT}
