// Code generated by "stringer -type=Type"; DO NOT EDIT.

package change

import "strconv"

const _Type_name = "UpdatedDeleted"

var _Type_index = [...]uint8{0, 7, 14}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
